### ISSUE TITLE
PostgreSQL concatenation error at schedules/Console.php file.

### ISSUE THREAD

**Issue by vanyabrovary** [panlatent/schedule#27]
The PostgreSQL concatenation operator syntax is different from the MySQL syntax.
In this regard, an error occurs in PostgreSQL.
Here is the code of my patch for PostgreSQL :

```
diff --git a/vendor/panlatent/schedule/src/schedules/Console.php b/vendor/panlatent/schedule/src/schedules/Console.php
--- a/vendor/panlatent/schedule/src/schedules/Console.php	
+++ b/vendor/panlatent/schedule/src/schedules/Console.php	(date 1718083081806)
@@ -156,7 +156,7 @@
             Craft::$app->getDb()->createCommand()
                 ->update(Table::SCHEDULELOGS, [
                     'status' => self::STATUS_PROCESSING,
-                    'output' => new Expression("CONCAT([[output]],:output)", ['output' => $output]),
+                    'output' => new Expression("output || :output", ['output' => $output]),
                 ], [
                     'id' => $logId,
                 ])

```

**Comment by vanyabrovary** [comment]
My PosqtgreSQL version is 16.

If i use:
`'output' => new Expression("CONCAT([[output]],:output)", ['output' => $output]),`

Instead of:
`'output' => new Expression("output || :output", ['output' => $output]),`

I got an error at storage/logs/console.log: 
```
SQLSTATE[22001]: String data, right truncated: 7 ERROR: value too long for type character varying(255)
The SQL being executed was: UPDATE "schedulelogs" SET "status"='failed', "reason"='SQLSTATE[42P18]: Indeterminate datatype: 7 ERROR: could not determine the data type of the parameter $2
The SQL being executed was: UPDATE "schedulelogs" SET "status"=''processing'', "output"=CONCAT(\"output\",''= \n''), "dateUpdated"=''2024-06-15 00:47:01'' WHERE "id"=140179', \"endTime\"=1718412421969, \"dateUpdated\"='2024-06-15 00:47:01' WHERE \"id\"=140179",
```

Also at CP (/admin/schedule/logs) schedule status is Preparing and log of this schedule is empty.
![log](https://github.com/panlatent/schedule/assets/13607532/f6639399-de1e-4754-96d0-7398db5c2692)
![logs](https://github.com/panlatent/schedule/assets/13607532/3817c119-1fbd-4ac9-8eba-b72a635a0b71)

I fixed this using a patch, but I thought it might be useful to you.

**Comment by vanyabrovary** [comment]
Also screenshot of schedule settings
![schedule](https://github.com/panlatent/schedule/assets/13607532/3b9d719a-c408-41a0-857a-86ef2a95db91)

**Comment by panlatent** [comment]
@vanyabrovary  

Thank you. You are right, I found the reason, fixed it and tested it in the local environment.

https://stackoverflow.com/questions/49033241/postgresql-sqlstate42p18-indeterminate-datatype-with-pdo-and-concat
