### ISSUE TITLE
Unable to run a queue job

### ISSUE THREAD

**Issue by punkch** [panlatent/schedule#4]
Hi,

First of all, thanks for the awesome plugin. It's really amazing! :)

I have a job in a module, and I am trying to set up a schedule with the default craft queue component (queue). However it always throws the "Invalid queue component" exception from src/schedules/Queue.php, because craft\queue\Queue extends from yii\queue\Queue.
Everything seems to work if I comment out the throw part.
Is there some typo with the $queue variable validation, or is it required to us a different Queue component?

Cheers!

```php
    protected function execute()
    {
        $queue = Craft::$app->get($this->componentId);
        if (!$queue || $queue instanceof \yii\queue\Queue || $queue instanceof QueueInterface) {
             throw new ScheduleException('Invalid queue component');
        }
        Craft::info("x__x");

        /** @var \yii\queue\Queue $queue */
        $job = new $this->jobClass();
        $queue->push($job);

        Craft::info("Queue Schedule push a job: {$this->jobClass} to {$this->componentId} component.", __METHOD__);
    }
```

**Comment by panlatent** [comment]
Thanks for using and feedback!

This is a conditional judgment causing a bug, I have fixed it in the latest code and plan to support more features about "queue".

I will release the official version (0.2.x) as soon as possible :D
